services:

  backend:
    build: ./backend
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - ./:/node_modules
    networks:
      - mern-app

  frontend:
    build: ./frontend
    stdin_open: true
    environment:
      - PORT=3000
      - BROWSER=none
      - HTTPS=false
    depends_on:
      - backend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./:/node_modules
    networks:
      - mern-app
      
  tests:
    build: ./
    container_name: test_runner 
    network_mode: "host"
    ports:
      - 8080:8080
    depends_on:
      - backend
      - frontend

volumes:
  data:


networks:
  mern-app: