name: Playwright Tests
on:
  push:
    branches: [ main, master ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: lts/*

      - name: Install Root Dependencies
        run: npm install

      - name: Install Frontend Dependencies
        run: npm run install:frontend

      - name: Install Backend Dependencies
        run: npm run install:backend

      - name: Install Playwright Browsers      
        run: npx playwright install --with-deps

      - name: Start Backend API
        run: nohup npm run start:backend > backend.log 2>&1 &
        env:
          CI: true
          MONGO_URI: "mongodb+srv://jadenbolton14:Marlo6872@testcluster.hincty3.mongodb.net/mydatabase?retryWrites=true&w=majority&appName=TestCluster"
          PORT: 4000

      - name: Show Backend Logs (if it fails)
        if: failure()
        run: cat backend.log
        

      - name: Start React Frontend
        run: npm --prefix frontend start &
        env:
          CI: true
          
      - name: Check if Frontend is Running
        run: curl -I http://localhost:3000 || exit 1
        
      - name: Check if Backend is Running
        run: curl -I http://localhost:4000 || exit 1

      - name: Wait for Services
        run: npx wait-on http://localhost:3000 http://localhost:4000

      - name: Run Playwright Tests
        run: npm run test