name: Playwright Tests
on:
  push:
    branches: [ main, master ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: lts/*

      - name: Install Root Dependencies
        run: npm install

      - name: Install Frontend Dependencies
        run: npm run install:frontend

      - name: Install Backend Dependencies
        run: npm run install:backend

      - name: Install Playwright Browsers      
        run: npx playwright install --with-deps
        
      - name: Get GitHub Runner IP
        id: ip
        run: echo "PUBLIC_IP=$(curl -s ifconfig.me)" >> $GITHUB_ENV

      - name: Add GitHub Actions IP to MongoDB Atlas
        run: |
          curl --user "your-atlas-username:your-atlas-api-key" \
          --digest \
          --header "Content-Type: application/json" \
          --request POST \
          --data "{\"ipAddress\": \"${{ env.PUBLIC_IP }}\"}" \
          "https://cloud.mongodb.com/api/atlas/v1.0/groups/YOUR_PROJECT_ID/accessList"


      - name: Start Backend API
        run: nohup npm run start:backend > backend.log 2>&1 &
        env:
          CI: true
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PORT: ${{ secrets.PORT }}

      - name: Start React Frontend
        run: npm --prefix frontend start &
        env:
          CI: true
          
      - name: Check if Frontend is Running
        run: curl -I http://localhost:3000 || exit 1
        
      - name: Check if Backend is Running
        run: curl -I http://localhost:4000 || exit 1

      - name: Wait for Services
        run: npx wait-on http://localhost:3000 http://localhost:4000

      - name: Run Playwright Tests
        run: npm run test